sed -i  '' 's/Arizona_elegans/I0066/g' besmptree.tre
sed -i  '' 's/Bogertophis_rosaliae/I0067/g' besmptree.tre
sed -i  '' 's/Bogertophis_subocularis/I0068/g' besmptree.tre
sed -i  '' 's/Cemophora_coccinea/I0069/g' besmptree.tre
sed -i  '' 's/Coelognathus_helena/I0070/g' besmptree.tre
sed -i  '' 's/Coelognathis_subradiatus/I0071/g' besmptree.tre
sed -i  '' 's/Coelognathus_erythrurus/I0072/g' besmptree.tre
sed -i  '' 's/Coelognathus_flavolineatus/I0073/g' besmptree.tre
sed -i  '' 's/Coelognathus_radiatus/I0074/g' besmptree.tre
sed -i  '' 's/Coronella_austriaca/I0075/g' besmptree.tre
sed -i  '' 's/Coronella_girondica/I0076/g' besmptree.tre
sed -i  '' 's/Elaphe_anomala/I0077/g' besmptree.tre
sed -i  '' 's/Elaphe_bimaculata/I0078/g' besmptree.tre
sed -i  '' 's/Elaphe_carinata/I0079/g' besmptree.tre
sed -i  '' 's/Elaphe_carinata2/I0080/g' besmptree.tre
sed -i  '' 's/Elaphe_climacophora/I0081/g' besmptree.tre
sed -i  '' 's/Elaphe_davidi/I0082/g' besmptree.tre
sed -i  '' 's/Elaphe_dione/I0083/g' besmptree.tre
sed -i  '' 's/Elaphe_dione2/I0084/g' besmptree.tre
sed -i  '' 's/Elaphe_quadrivirgata/I0085/g' besmptree.tre
sed -i  '' 's/Elaphe_quatuorlineata/I0086/g' besmptree.tre
sed -i  '' 's/Elaphe_schrenckii/I0087/g' besmptree.tre
sed -i  '' 's/Elaphe_zoigeensis/I0088/g' besmptree.tre
sed -i  '' 's/Euprepiophis_conspicillatus/I0089/g' besmptree.tre
sed -i  '' 's/Euprepiophis_mandarinus/I0090/g' besmptree.tre
sed -i  '' 's/Euprepiophis_mandarinus2/I0091/g' besmptree.tre
sed -i  '' 's/Euprepiophis_perlaceus/I0092/g' besmptree.tre
sed -i  '' 's/Gonyosoma_oxycephalum/I0093/g' besmptree.tre
sed -i  '' 's/Lampropeltis_alterna/I0094/g' besmptree.tre
sed -i  '' 's/Lampropeltis_californiae/I0095/g' besmptree.tre
sed -i  '' 's/Lampropeltis_rhombomaculata/I0096/g' besmptree.tre
sed -i  '' 's/Euprepiophis_mandarinus3/I0097/g' besmptree.tre
sed -i  '' 's/Lampropeltis_calligaster/I0098/g' besmptree.tre
sed -i  '' 's/Lampropeltis_elapsoides/I0099/g' besmptree.tre
sed -i  '' 's/Lampropeltis_extenuata/I0100/g' besmptree.tre
sed -i  '' 's/Lampropeltis_getula/I0101/g' besmptree.tre
sed -i  '' 's/Lampropeltis_holbrooki/I0102/g' besmptree.tre
sed -i  '' 's/Lampropeltis_knoblochi/I0103/g' besmptree.tre
sed -i  '' 's/Lampropeltis_mexicana/I0104/g' besmptree.tre
sed -i  '' 's/Lampropeltis_nigra/I0105/g' besmptree.tre
sed -i  '' 's/Lampropeltis_pyromelana/I0106/g' besmptree.tre
sed -i  '' 's/Lampropeltis_ruthveni/I0107/g' besmptree.tre
sed -i  '' 's/Lampropeltis_splendida/I0108/g' besmptree.tre
sed -i  '' 's/Lampropeltis_abnorma/I0109/g' besmptree.tre
sed -i  '' 's/Lampropeltis_polyzona/I0110/g' besmptree.tre
sed -i  '' 's/Nerodia_sipedon/I0111/g' besmptree.tre
sed -i  '' 's/Lampropeltis_micropholis/I0112/g' besmptree.tre
sed -i  '' 's/Lampropeltis_annulata/I0113/g' besmptree.tre
sed -i  '' 's/Lampropeltis_gentilis/I0114/g' besmptree.tre
sed -i  '' 's/Lampropeltis_webbi/I0115/g' besmptree.tre
sed -i  '' 's/Lampropeltis_zonata/I0116/g' besmptree.tre
sed -i  '' 's/Lampropeltis_multifasciata/I0117/g' besmptree.tre
sed -i  '' 's/Archelaphe_bella/I0118/g' besmptree.tre
sed -i  '' 's/Oocatochus_rufodorsatus/I0119/g' besmptree.tre
sed -i  '' 's/Oreocryptophis_porphyraceus/I0120/g' besmptree.tre
sed -i  '' 's/Oreocryptophis_porphyraceus2/I0121/g' besmptree.tre
sed -i  '' 's/Orthriophis_cantoris/I0122/g' besmptree.tre
sed -i  '' 's/Orthriophis_hodgsoni/I0123/g' besmptree.tre
sed -i  '' 's/Orthriophis_moellendorffi/I0124/g' besmptree.tre
sed -i  '' 's/Orthriophis_taeniurus/I0125/g' besmptree.tre
sed -i  '' 's/Heterodon_platirhinos/I0126/g' besmptree.tre
sed -i  '' 's/Pantherophis_bairdi/I0127/g' besmptree.tre
sed -i  '' 's/Pantherophis_emoryi/I0128/g' besmptree.tre
sed -i  '' 's/Pantherophis_guttatus/I0129/g' besmptree.tre
sed -i  '' 's/Pantherophis_obsoletus/I0130/g' besmptree.tre
sed -i  '' 's/Pantherophis_ramspotti/I0131/g' besmptree.tre
sed -i  '' 's/Pantherophis_slowinskii/I0132/g' besmptree.tre
sed -i  '' 's/Pantherophis_spiloides/I0133/g' besmptree.tre
sed -i  '' 's/Pantherophis_vulpinus_hybrid/I0134/g' besmptree.tre
sed -i  '' 's/Pituophis_catenifer/I0135/g' besmptree.tre
sed -i  '' 's/Pituophis_deppei/I0136/g' besmptree.tre
sed -i  '' 's/Pituophis_lineaticollis/I0137/g' besmptree.tre
sed -i  '' 's/Pituophis_melanoleucus/I0138/g' besmptree.tre
sed -i  '' 's/Pituophis_ruthveni/I0139/g' besmptree.tre
sed -i  '' 's/Pituophis_vertebralis/I0140/g' besmptree.tre
sed -i  '' 's/Pseudelaphe_flavirufa/I0141/g' besmptree.tre
sed -i  '' 's/Gonyosoma_frenatum/I0142/g' besmptree.tre
sed -i  '' 's/Gonyosoma_prasinum/I0143/g' besmptree.tre
sed -i  '' 's/Rhinechis_scalaris/I0144/g' besmptree.tre
sed -i  '' 's/Rhinocheilus_lecontei/I0145/g' besmptree.tre
sed -i  '' 's/Gonyosoma_boulengeri/I0146/g' besmptree.tre
sed -i  '' 's/Senticolis_triaspis/I0147/g' besmptree.tre
sed -i  '' 's/Zamenis_hohenackeri/I0148/g' besmptree.tre
sed -i  '' 's/Zamenis_lineatus/I0149/g' besmptree.tre
sed -i  '' 's/Zamenis_longissimus/I0150/g' besmptree.tre
sed -i  '' 's/Zamenis_persicus/I0151/g' besmptree.tre
sed -i  '' 's/Zamenis_situla/I0152/g' besmptree.tre
sed -i  '' 's/Coluber_constrictor/I0153/g' besmptree.tre
sed -i  '' 's/Drymobius_margaritiferus/I0154/g' besmptree.tre
sed -i  '' 's/Gyalopion_canum/I0155/g' besmptree.tre
sed -i  '' 's/Hapsidophrys_lineatus/I0156/g' besmptree.tre
sed -i  '' 's/Hemorrhois_ravergieri/I0157/g' besmptree.tre
sed -i  '' 's/Ptyas_mucosa/I0158/g' besmptree.tre
sed -i  '' 's/Tantilla_coronata/I0159/g' besmptree.tre