sed -i  '' 's/I0066/Arizona_elegans/g' g6_pp_mp.tre
sed -i  '' 's/I0067/Bogertophis_rosaliae/g' g6_pp_mp.tre
sed -i  '' 's/I0068/Bogertophis_subocularis/g' g6_pp_mp.tre
sed -i  '' 's/I0069/Cemophora_coccinea/g' g6_pp_mp.tre
sed -i  '' 's/I0070/Coelegnathus_helena/g' g6_pp_mp.tre
sed -i  '' 's/I0071/Coelognathis_subradiatus/g' g6_pp_mp.tre
sed -i  '' 's/I0072/Coelognathus_erythrurus/g' g6_pp_mp.tre
sed -i  '' 's/I0073/Coelognathus_flavolineatus/g' g6_pp_mp.tre
sed -i  '' 's/I0074/Coelognathus_radiatus/g' g6_pp_mp.tre
sed -i  '' 's/I0075/Coronella_austriaca/g' g6_pp_mp.tre
sed -i  '' 's/I0076/Coronella_girondica/g' g6_pp_mp.tre
sed -i  '' 's/I0077/Elaphe_anomala/g' g6_pp_mp.tre
sed -i  '' 's/I0078/Elaphe_bimaculata/g' g6_pp_mp.tre
sed -i  '' 's/I0079/Elaphe_carinata/g' g6_pp_mp.tre
sed -i  '' 's/I0080/Elaphe_carinata2/g' g6_pp_mp.tre
sed -i  '' 's/I0081/Elaphe_climacophora/g' g6_pp_mp.tre
sed -i  '' 's/I0082/Elaphe_davidi/g' g6_pp_mp.tre
sed -i  '' 's/I0083/Elaphe_dione/g' g6_pp_mp.tre
sed -i  '' 's/I0084/Elaphe_dione2/g' g6_pp_mp.tre
sed -i  '' 's/I0085/Elaphe_quadrivirgata/g' g6_pp_mp.tre
sed -i  '' 's/I0086/Elaphe_quatuorlineata/g' g6_pp_mp.tre
sed -i  '' 's/I0087/Elaphe_schrenckii/g' g6_pp_mp.tre
sed -i  '' 's/I0088/Elaphe_zoigeensis/g' g6_pp_mp.tre
sed -i  '' 's/I0089/Euprepiophis_conspicillatus/g' g6_pp_mp.tre
sed -i  '' 's/I0090/Euprepiophis_mandarinus/g' g6_pp_mp.tre
sed -i  '' 's/I0091/Euprepiophis_mandarinus2/g' g6_pp_mp.tre
sed -i  '' 's/I0092/Euprepiophis_perlaceus/g' g6_pp_mp.tre
sed -i  '' 's/I0093/Gonyosoma_oxycephalum/g' g6_pp_mp.tre
sed -i  '' 's/I0094/Lampropeltis_alterna/g' g6_pp_mp.tre
sed -i  '' 's/I0095/Lampropeltis_californiae/g' g6_pp_mp.tre
sed -i  '' 's/I0096/Lampropeltis_rhombomaculata/g' g6_pp_mp.tre
sed -i  '' 's/I0097/Euprepiophis_mandarinus3/g' g6_pp_mp.tre
sed -i  '' 's/I0098/Lampropeltis_calligaster/g' g6_pp_mp.tre
sed -i  '' 's/I0099/Lampropeltis_elapsoides/g' g6_pp_mp.tre
sed -i  '' 's/I0100/Lampropeltis_extenuata/g' g6_pp_mp.tre
sed -i  '' 's/I0101/Lampropeltis_getula/g' g6_pp_mp.tre
sed -i  '' 's/I0102/Lampropeltis_holbrooki/g' g6_pp_mp.tre
sed -i  '' 's/I0103/Lampropeltis_knoblochi/g' g6_pp_mp.tre
sed -i  '' 's/I0104/Lampropeltis_mexicana/g' g6_pp_mp.tre
sed -i  '' 's/I0105/Lampropeltis_nigra/g' g6_pp_mp.tre
sed -i  '' 's/I0106/Lampropeltis_pyromelana/g' g6_pp_mp.tre
sed -i  '' 's/I0107/Lampropeltis_ruthveni/g' g6_pp_mp.tre
sed -i  '' 's/I0108/Lampropeltis_splendida/g' g6_pp_mp.tre
sed -i  '' 's/I0109/Lampropeltis_abnorma/g' g6_pp_mp.tre
sed -i  '' 's/I0110/Lampropeltis_polyzona/g' g6_pp_mp.tre
sed -i  '' 's/I0111/Nerodia_sipedon/g' g6_pp_mp.tre
sed -i  '' 's/I0112/Lampropeltis_micropholis/g' g6_pp_mp.tre
sed -i  '' 's/I0113/Lampropeltis_annulata/g' g6_pp_mp.tre
sed -i  '' 's/I0114/Lampropeltis_gentilis/g' g6_pp_mp.tre
sed -i  '' 's/I0115/Lampropeltis_webbi/g' g6_pp_mp.tre
sed -i  '' 's/I0116/Lampropeltis_zonata/g' g6_pp_mp.tre
sed -i  '' 's/I0117/Lampropeltis_multifasciata/g' g6_pp_mp.tre
sed -i  '' 's/I0118/Archelaphe_bella/g' g6_pp_mp.tre
sed -i  '' 's/I0119/Oocatochus_rufodorsatus/g' g6_pp_mp.tre
sed -i  '' 's/I0120/Oreocryptophis_porphyraceus/g' g6_pp_mp.tre
sed -i  '' 's/I0121/Oreocryptophis_porphyraceus2/g' g6_pp_mp.tre
sed -i  '' 's/I0122/Orthriophis_cantoris/g' g6_pp_mp.tre
sed -i  '' 's/I0123/Orthriophis_hodgsoni/g' g6_pp_mp.tre
sed -i  '' 's/I0124/Orthriophis_moellendorffi/g' g6_pp_mp.tre
sed -i  '' 's/I0125/Orthriophis_taeniurus/g' g6_pp_mp.tre
sed -i  '' 's/I0126/Heterodon_platirhinos/g' g6_pp_mp.tre
sed -i  '' 's/I0127/Pantherophis_bairdi/g' g6_pp_mp.tre
sed -i  '' 's/I0128/Pantherophis_emoryi/g' g6_pp_mp.tre
sed -i  '' 's/I0129/Pantherophis_guttatus/g' g6_pp_mp.tre
sed -i  '' 's/I0130/Pantherophis_obsoletus/g' g6_pp_mp.tre
sed -i  '' 's/I0131/Pantherophis_ramspotti/g' g6_pp_mp.tre
sed -i  '' 's/I0132/Pantherophis_slowinskii/g' g6_pp_mp.tre
sed -i  '' 's/I0133/Pantherophis_spiloides/g' g6_pp_mp.tre
sed -i  '' 's/I0134/Pantherophis_vulpinus_hybrid/g' g6_pp_mp.tre
sed -i  '' 's/I0135/Pituophis_catenifer/g' g6_pp_mp.tre
sed -i  '' 's/I0136/Pituophis_deppei/g' g6_pp_mp.tre
sed -i  '' 's/I0137/Pituophis_lineaticollis/g' g6_pp_mp.tre
sed -i  '' 's/I0138/Pituophis_melanoleucus/g' g6_pp_mp.tre
sed -i  '' 's/I0139/Pituophis_ruthveni/g' g6_pp_mp.tre
sed -i  '' 's/I0140/Pituophis_vertebralis/g' g6_pp_mp.tre
sed -i  '' 's/I0141/Pseudelaphe_flavirufa/g' g6_pp_mp.tre
sed -i  '' 's/I0142/Gonyosoma_frenatum/g' g6_pp_mp.tre
sed -i  '' 's/I0143/Gonyosoma_prasinum/g' g6_pp_mp.tre
sed -i  '' 's/I0144/Rhinechis_scalaris/g' g6_pp_mp.tre
sed -i  '' 's/I0145/Rhinocheilus_lecontei/g' g6_pp_mp.tre
sed -i  '' 's/I0146/Gonyosoma_boulengeri/g' g6_pp_mp.tre
sed -i  '' 's/I0147/Senticolis_triaspis/g' g6_pp_mp.tre
sed -i  '' 's/I0148/Zamenis_hohenackeri/g' g6_pp_mp.tre
sed -i  '' 's/I0149/Zamenis_lineatus/g' g6_pp_mp.tre
sed -i  '' 's/I0150/Zamenis_longissimus/g' g6_pp_mp.tre
sed -i  '' 's/I0151/Zamenis_persicus/g' g6_pp_mp.tre
sed -i  '' 's/I0152/Zamenis_situla/g' g6_pp_mp.tre
sed -i  '' 's/I0153/Coluber_constrictor/g' g6_pp_mp.tre
sed -i  '' 's/I0154/Drymobius_margaritiferus/g' g6_pp_mp.tre
sed -i  '' 's/I0155/Gyalopion_canum/g' g6_pp_mp.tre
sed -i  '' 's/I0156/Hapsidophrys_lineatus/g' g6_pp_mp.tre
sed -i  '' 's/I0157/Hemorrhois_ravergieri/g' g6_pp_mp.tre
sed -i  '' 's/I0158/Ptyas_mucosa/g' g6_pp_mp.tre
sed -i  '' 's/I0159/Tantilla_coronata/g' g6_pp_mp.tre