find . -name '*gene_1.txt' -delete
find . -name '*gene_101.txt' -delete
find . -name '*gene_102.txt' -delete
find . -name '*gene_106.txt' -delete
find . -name '*gene_107.txt' -delete
find . -name '*gene_114.txt' -delete
find . -name '*gene_119.txt' -delete
find . -name '*gene_12.txt' -delete
find . -name '*gene_121.txt' -delete
find . -name '*gene_135.txt' -delete
find . -name '*gene_136.txt' -delete
find . -name '*gene_139.txt' -delete
find . -name '*gene_141.txt' -delete
find . -name '*gene_146.txt' -delete
find . -name '*gene_147.txt' -delete
find . -name '*gene_148.txt' -delete
find . -name '*gene_156.txt' -delete
find . -name '*gene_16.txt' -delete
find . -name '*gene_169.txt' -delete
find . -name '*gene_175.txt' -delete
find . -name '*gene_177.txt' -delete
find . -name '*gene_193.txt' -delete
find . -name '*gene_2.txt' -delete
find . -name '*gene_205.txt' -delete
find . -name '*gene_211.txt' -delete
find . -name '*gene_213.txt' -delete
find . -name '*gene_221.txt' -delete
find . -name '*gene_226.txt' -delete
find . -name '*gene_227.txt' -delete
find . -name '*gene_228.txt' -delete
find . -name '*gene_229.txt' -delete
find . -name '*gene_232.txt' -delete
find . -name '*gene_237.txt' -delete
find . -name '*gene_238.txt' -delete
find . -name '*gene_241.txt' -delete
find . -name '*gene_248.txt' -delete
find . -name '*gene_25.txt' -delete
find . -name '*gene_251.txt' -delete
find . -name '*gene_26.txt' -delete
find . -name '*gene_261.txt' -delete
find . -name '*gene_273.txt' -delete
find . -name '*gene_275.txt' -delete
find . -name '*gene_282.txt' -delete
find . -name '*gene_295.txt' -delete
find . -name '*gene_296.txt' -delete
find . -name '*gene_298.txt' -delete
find . -name '*gene_303.txt' -delete
find . -name '*gene_307.txt' -delete
find . -name '*gene_312.txt' -delete
find . -name '*gene_319.txt' -delete
find . -name '*gene_32.txt' -delete
find . -name '*gene_321.txt' -delete
find . -name '*gene_324.txt' -delete
find . -name '*gene_330.txt' -delete
find . -name '*gene_334.txt' -delete
find . -name '*gene_335.txt' -delete
find . -name '*gene_344.txt' -delete
find . -name '*gene_347.txt' -delete
find . -name '*gene_350.txt' -delete
find . -name '*gene_355.txt' -delete
find . -name '*gene_358.txt' -delete
find . -name '*gene_363.txt' -delete
find . -name '*gene_365.txt' -delete
find . -name '*gene_372.txt' -delete
find . -name '*gene_38.txt' -delete
find . -name '*gene_380.txt' -delete
find . -name '*gene_387.txt' -delete
find . -name '*gene_40.txt' -delete
find . -name '*gene_400.txt' -delete
find . -name '*gene_52.txt' -delete
find . -name '*gene_56.txt' -delete
find . -name '*gene_7.txt' -delete
find . -name '*gene_74.txt' -delete
find . -name '*gene_82.txt' -delete
find . -name '*gene_85.txt' -delete
find . -name '*gene_91.txt' -delete