find . -name '*gene_352.txt' -delete
find . -name '*gene_306.txt' -delete
find . -name '*gene_59.txt' -delete
find . -name '*gene_34.txt' -delete
find . -name '*gene_350.txt' -delete
find . -name '*gene_138.txt' -delete
find . -name '*gene_178.txt' -delete
find . -name '*gene_64.txt' -delete
find . -name '*gene_140.txt' -delete
find . -name '*gene_283.txt' -delete
find . -name '*gene_28.txt' -delete
find . -name '*gene_214.txt' -delete
find . -name '*gene_257.txt' -delete
find . -name '*gene_273.txt' -delete
find . -name '*gene_98.txt' -delete
find . -name '*gene_310.txt' -delete
find . -name '*gene_246.txt' -delete
find . -name '*gene_304.txt' -delete
find . -name '*gene_102.txt' -delete
find . -name '*gene_256.txt' -delete
find . -name '*gene_321.txt' -delete
find . -name '*gene_200.txt' -delete
find . -name '*gene_211.txt' -delete
find . -name '*gene_252.txt' -delete
find . -name '*gene_44.txt' -delete
find . -name '*gene_40.txt' -delete
find . -name '*gene_60.txt' -delete
find . -name '*gene_305.txt' -delete
find . -name '*gene_232.txt' -delete
find . -name '*gene_144.txt' -delete
find . -name '*gene_368.txt' -delete
find . -name '*gene_128.txt' -delete
find . -name '*gene_182.txt' -delete
find . -name '*gene_347.txt' -delete
find . -name '*gene_260.txt' -delete
find . -name '*gene_249.txt' -delete
find . -name '*gene_55.txt' -delete